"""empty message

Revision ID: 53828bf319c0
Revises: 9e98a00a0ef2
Create Date: 2026-03-31 20:03:06.847910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53828bf319c0'
down_revision = '9e98a00a0ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('terrain', sa.String(length=120), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
